name: Build Talos RPi5 Image

on:
    workflow_dispatch:
        inputs:
            talos_version:
                description: "Talos version"
                required: true
                default: "v1.11.0"

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: failuretoload/talos-rpi5

jobs:
    build:
        runs-on: ubuntu-24.04-arm
        permissions:
            contents: read
            packages: write

        steps:
            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push installer
              run: |
                  docker run --rm \
                    --volume $(pwd)/out:/out \
                    ghcr.io/talos-rpi5/imager:v1.10.7-1-g5893396e8 \
                    installer \
                    --arch arm64 \
                    --overlay-image ghcr.io/talos-rpi5/sbc-raspberrypi5:7d04484-v1.10.0-1-gf7d2f72 \
                    --overlay-name rpi5 \
                    --system-extension-image ghcr.io/siderolabs/iscsi-tools:v0.2.0 \
                    --system-extension-image ghcr.io/siderolabs/util-linux-tools:2.41.1

                  docker load -i out/installer-arm64.tar
                  docker tag ghcr.io/talos-rpi5/installer-base:v1.10.7-1-g5893396e8 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:custom
                  docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:custom