apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cilium-selfsigned
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cilium-ca
  namespace: cilium
spec:
  isCA: true
  commonName: Cilium CA
  secretName: cilium-ca
  duration: 26280h # 3 years
  renewBefore: 720h # 30 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: cilium-selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cilium-ca-issuer
  namespace: cilium
spec:
  ca:
    secretName: cilium-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-server-certs
  namespace: cilium
spec:
  secretName: hubble-server-certs
  duration: 8760h # 1 year
  renewBefore: 720h # 30 days
  commonName: "*.default.hubble-grpc.cilium.io"
  dnsNames:
    - "*.default.hubble-grpc.cilium.io"
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  issuerRef:
    name: cilium-ca-issuer
    kind: Issuer
    group: cert-manager.io
