apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.18.0
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    ipam:
      mode: kubernetes
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    operator:
      replicas: 2
    tls:
      ca:
        certValidityDuration: 1095
      secretsNamespace:
        create: false
        name: cilium
    hubble:
      enabled: true
      tls:
        enabled: true
        auto:
          enabled: true
          method: certmanager
          certManagerIssuerRef:
            group: cert-manager.io
            kind: Issuer
            name: cilium-ca-issuer
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - IPC_LOCK
          - KILL
          - NET_ADMIN
          - NET_RAW
          - SETGID
          - SETUID
          - SYS_ADMIN
          - SYS_RESOURCE
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
