apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-db
  namespace: postgres
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    storageClass: longhorn
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
