apiVersion: v1
kind: Namespace
metadata:
  name: core-networking
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: core-networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-keyvault
    kind: ClusterSecretStore
  target:
    name: cloudflared-tunnel-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: cloudflared-tunnel-token