apiVersion: v1
kind: Namespace
metadata:
  name: datamonster
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: acr-credentials
  namespace: datamonster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  target:
    name: acr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"{{ .server }}":{"username":"{{ .username }}","password":"{{ .password }}"}}}
  data:
    - secretKey: server
      remoteRef:
        key: acr-login-server
    - secretKey: username
      remoteRef:
        key: acr-user
    - secretKey: password
      remoteRef:
        key: acr-pass
