apiVersion: v1
kind: Namespace
metadata:
  name: datamonster
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: datamonster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: ghcr-user
    - secretKey: password
      remoteRef:
        key: ghcr-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: datamonster-oidc
  namespace: datamonster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets
    kind: ClusterSecretStore
  target:
    name: datamonster-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: datamonster-oidc-secret
