apiVersion: v1
kind: Namespace
metadata:
  name: observe
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: observe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets
  target:
    name: grafana
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana-admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana-admin-password
