apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    replicaCount: 2
    bitwarden-sdk-server:
      enabled: true
      namespace: external-secrets
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
    webhook:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
    certController:
      replicaCount: 2
      podDisruptionBudget:
        enabled: true
        minAvailable: 1
