apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.90.8
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    commonLabels:
      app.kubernetes.io/name: tailscale
    oauth: {}
    operatorConfig:
      hostname: homelab-k8s-operator
      defaultTags:
        - "tag:k8s-operator"
    apiServerProxyConfig:
      mode: "false"
    proxyConfig:
      defaultTags: "tag:k8s"
    podAnnotations:
      io.cilium.no-track-port: "41641"
