apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale
  namespace: core-argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: core-tailscale
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[].remoteRef.conversionStrategy
        - .spec.data[].remoteRef.decodingStrategy
        - .spec.data[].remoteRef.metadataPolicy
        - .spec.target.deletionPolicy
        - .spec.refreshInterval
  sources:
    - repoURL: https://pkgs.tailscale.com/helmcharts
      chart: tailscale-operator
      targetRevision: 1.90.8
      helm:
        releaseName: tailscale-operator
        valueFiles:
          - $values/cluster/resources/tailscale/values.yaml
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
