apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: core-argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-image-updater
      targetRevision: 1.0.1
      helm:
        releaseName: argocd-image-updater
        valueFiles:
          - $values/cluster/resources/image-updater/values.yaml
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      ref: values
      path: cluster/resources/image-updater
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
