apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  sources:
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      path: cluster/resources/cloudflared
  destination:
    name: in-cluster
    namespace: core-networking
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
