apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: origin-ca-issuer-crds
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: core-networking
  sources:
    - repoURL: https://github.com/cloudflare/origin-ca-issuer.git
      targetRevision: v0.13.0
      path: deploy/crds
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - ServerSideApply=true
