apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: core-observe
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.46.0
      helm:
        releaseName: loki
        valueFiles:
          - $values/cluster/resources/loki/values.yaml
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
