apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: core-observe
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.2.0
      helm:
        releaseName: grafana
        valueFiles:
          - $values/cluster/resources/grafana/values.yaml
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:FailureToLoad/homelab-cluster.git
      targetRevision: main
      path: cluster/resources/grafana
      directory:
        exclude: "{values.yaml,external-secret.yaml}"
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
