apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: core-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: git@github.com:FailureToLoad/homelab-cluster.git
    targetRevision: main
    path: cluster/namespaces
  destination:
    name: in-cluster
    namespace: core-argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: true
