apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: core-auth
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lldap-config
  namespace: core-auth
data:
  LLDAP_LDAP_BASE_DN: "dc=homelab,dc=local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  namespace: core-auth
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      containers:
        - name: lldap
          image: lldap/lldap:v0.6.2
          ports:
            - containerPort: 3890
            - containerPort: 17170
          envFrom:
            - configMapRef:
                name: lldap-config
            - secretRef:
                name: lldap-secrets
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: lldap-data
---
apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: core-auth
spec:
  selector:
    app.kubernetes.io/name: lldap
  ports:
    - name: ldap
      port: 389
      targetPort: 3890
    - name: http
      port: 17170
      targetPort: 17170
