apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: origin-ca-issuer
  namespace: edge
spec:
  interval: 30m
  chart:
    spec:
      chart: origin-ca-issuer
      version: 0.5.10
      sourceRef:
        kind: HelmRepository
        name: origin-ca-issuer
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    certmanager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    controller:
      replicaCount: 1
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
